"use client";

import { useMemo, useState, type ComponentType } from "react";
import { Cpu, FolderDown, Layers, Maximize2, Palette, Printer, Scissors, Shirt, Sparkles, SunMedium, Zap, X } from "lucide-react";
import { SERVICE_CATEGORIES, getServiceLabel, type ServiceId } from "@/constants/services";
import { cn } from "@/lib/utils";

const icons: Record<string, ComponentType<{ size?: number; className?: string }>> = { banner_print: Printer, sticker_white: Layers, sticker_transparent: Maximize2, sticker_reflective: Sparkles, sticker_mesh: Layers, sticker_frosted: Sparkles, hq_print_and_cut: Scissors, light_box_a1: SunMedium, light_box_a2: SunMedium, neon_light: Zap, roll_up_standard: FolderDown, roll_up_deluxe: FolderDown, uv_print_mica: Palette, uv_print_foam: Palette, uv_print_cladding: Palette, uv_print_canvas: Palette, foam_cutout: Cpu, foam_engrave: Cpu, mica_cutout: Scissors, mica_engrave: Scissors, dtf: Shirt, sublimation: Shirt };
const categories = [{ id: "ALL", label: "ሁሉም" }, { id: "LARGE_FORMAT_PRINTING", label: "ባነር እና ስቲከር" }, { id: "SIGNAGE_AND_DISPLAYS", label: "ማስታወቂያ ቦርድ" }, { id: "FLATBED_UV_PRINTING", label: "UV ህትመት" }, { id: "CNC_AND_LASER", label: "ከት እና ቅርጽ" }, { id: "TEXTILE_AND_APPAREL", label: "DTF ጨርቃጨርቅ" }] as const;

export function ServicePicker({ value, onChange, onClear }: { value: ServiceId | null; onChange: (value: ServiceId) => void; onClear: () => void }) {
  const [category, setCategory] = useState("ALL");
  const visible = useMemo(() => category === "ALL" ? SERVICE_CATEGORIES : SERVICE_CATEGORIES.filter((item) => item.categoryId === category), [category]);
  const selectedItem = value ? SERVICE_CATEGORIES.flatMap((group) => group.items).find((item) => item.id === value) : undefined;
  if (selectedItem) {
    const Icon = icons[selectedItem.id] ?? Printer;
    return <section className="space-y-3"><div className="flex items-center justify-between border-b border-white/[0.08] pb-2"><span className="font-mono text-[11px] font-semibold text-neutral-300">01. የተመረጠ አገልግሎት</span><button type="button" onClick={onClear} className="flex items-center gap-1 rounded border border-emerald-500/50 px-2 py-1 text-xs text-emerald-400"><X size={13} /> ምርጫውን አጽዳ</button></div><div className="rounded border-2 border-emerald-500 bg-emerald-500/10 p-4"><div className="flex items-center gap-3"><Icon size={20} className="text-emerald-400" /><div><span className="block text-sm font-bold text-white">{getServiceLabel(selectedItem.id, "am") ?? selectedItem.label}</span><span className="font-mono text-xs text-neutral-400">{selectedItem.label}</span></div></div></div></section>;
  }
  return <section className="space-y-3"><div className="flex items-center justify-between border-b border-white/[0.08] pb-2"><span className="font-mono text-[11px] font-semibold text-neutral-300">01. የህትመት አይነት</span><span className="font-mono text-[10px] text-neutral-400">{SERVICE_CATEGORIES.flatMap((c) => c.items).length} አይነት</span></div><div className="flex gap-1 bg-[#131418] border border-white/[0.08] p-1 rounded-sm overflow-x-auto">{categories.map((item) => <button type="button" key={item.id} onClick={() => setCategory(item.id)} className={cn("font-mono text-[11px] px-3 py-1.5 rounded-sm whitespace-nowrap", category === item.id ? "bg-[#202228] text-white border border-white/[0.12]" : "text-neutral-400")}>{item.label}</button>)}</div><div className="space-y-4">{visible.map((group) => <div key={group.categoryId} className="space-y-2"><div className="font-mono text-[10px] text-neutral-400">{group.categoryName}</div><div className="grid grid-cols-2 gap-2">{group.items.map((item) => { const Icon = icons[item.id] ?? Printer; return <button type="button" key={item.id} onClick={() => onChange(item.id)} className="relative min-h-[76px] rounded-sm border border-white/[0.08] bg-[#131418] p-3 text-left text-neutral-300"><div className="mb-2"><Icon size={14} className="text-neutral-400" /></div><span className="block text-xs font-semibold">{getServiceLabel(item.id, "am") ?? item.label}</span><span className="mt-0.5 block truncate font-mono text-[10px] text-neutral-400">{item.label}</span></button>; })}</div></div>)}</div></section>;
}
